### ISSUE TITLE
你好，无意发现你的脚本，不敢fork，自行建库

### ISSUE THREAD

**Issue by 735450178** [Arrogance-H/Scripts#1]
你好，无意发现你的脚本，不敢fork，自行建库，可是设置了，secret运行报错，经过我自己的查看后发现错误出现再下图中，我尝试搜索解决，无果，希望您能抽空解答一下，抱拳，谢谢
![4Y7(5IVR}NGBIU2SG{X4ISS](https://user-images.githubusercontent.com/64771597/108307024-4c37aa80-71e8-11eb-971d-0716f38449d3.png)

**Comment by Arrogance-H** [comment]
自行检查代码是否正确完整。
